import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";
import PrelineScript from "@/components/preline-script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="mx-auto max-w-7xl">{children}</main>

        <PrelineScript />
        {draftMode().isEnabled && (
          <>
            <div>
              <a className="block bg-blue-300 p-4" href="/api/disable-draft">
                Disable preview mode
              </a>
            </div>
            <VisualEditing />
          </>
        )}
      </body>
    </html>
  );
}
